services:

  db:
    image: postgres
    container_name: mcp-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mcp-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root