"""init

Revision ID: f00252262af1
Revises: c8e34cf849b9
Create Date: 2025-09-24 01:53:41.915785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f00252262af1"
down_revision: Union[str, Sequence[str], None] = "c8e34cf849b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("chunks_manual_id_fkey"), "chunks", type_="foreignkey")
    op.create_foreign_key(
        None, "chunks", "manuals", ["manual_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chunks", type_="foreignkey")
    op.create_foreign_key(
        op.f("chunks_manual_id_fkey"), "chunks", "manuals", ["manual_id"], ["id"]
    )
    # ### end Alembic commands ###
